name: Run Python Unit Test

on:
  workflow_call:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        version: ['3.8', '3.10', '3.x']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout latest commit
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run tests
      run: |
        pytest -vrP
