name: Run Python Unit Test

on:
  workflow_call:
  push:
    branches: [test-prev]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        version: ['3.8', '3.10', '3.x']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout 0.2.3
      uses: actions/checkout@v4
      with:
        ref: '0.2.3'
        fetch-depth: 0
        fetch-tags: true
    - name: Checkout latest commit
      uses: actions/checkout@v4
      with:
        path: latest
    - shell: bash
      run: |
        rm -rf tests
        cp -r latest/tests tests/
        rm -rf latest
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install opencc pygtrie
        python preprocess.py
        pip install pytest pytest-subtests
    - name: Run tests
      run: |
        pytest -vrP
